# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/core33g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/core33g/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/core33g/proprietary/bin/npsmobex:system/bin/npsmobex \
    vendor/samsung/core33g/proprietary/bin/refnotify:system/bin/refnotify \
    vendor/samsung/core33g/proprietary/bin/engpc:system/bin/engpc \
    vendor/samsung/core33g/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/core33g/proprietary/lib/libsamsungearcare.so:system/lib/libsamsungearcare.so \
    vendor/samsung/core33g/proprietary/lib/libsamsungeffect.so:system/lib/libsamsungeffect.so \
    vendor/samsung/core33g/proprietary/lib/libSamsungPkcs11Wrapper.so:system/lib/libSamsungPkcs11Wrapper.so \
    vendor/samsung/core33g/proprietary/lib/libsamsungpowersound.so:system/lib/libsamsungpowersound.so \
    vendor/samsung/core33g/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/core33g/proprietary/lib/libsprd_agps_agent.so:system/lib/libsprd_agps_agent.so \
    vendor/samsung/core33g/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/core33g/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/samsung/core33g/proprietary/lib/libboost.so:system/lib/libboost.so \
    vendor/samsung/core33g/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/samsung/core33g/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/core33g/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/samsung/core33g/proprietary/etc/audio_hw.xml:system/etc/audio_hw.xml \
    vendor/samsung/core33g/proprietary/etc/audio_para:system/etc/audio_para \
    vendor/samsung/core33g/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/samsung/core33g/proprietary/etc/codec_pga.xml:system/etc/codec_pga.xml \
    vendor/samsung/core33g/proprietary/etc/tiny_hw.xml:system/etc/tiny_hw.xml \
    vendor/samsung/core33g/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/core33g/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/core33g/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/core33g/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/core33g/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/core33g/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/core33g/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/core33g/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/core33g/proprietary/vendor/firmware/BCM4330B1_002.001.003.1025.1303.hcd:system/vendor/firmware/BCM4330B1_002.001.003.1025.1303.hcd \
    vendor/samsung/core33g/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/core33g/proprietary/bin/modemd:system/bin/modemd \
    vendor/samsung/core33g/proprietary/bin/nvitemd:system/bin/nvitemd \
    vendor/samsung/core33g/proprietary/bin/phoneserver:system/bin/phoneserver \
    vendor/samsung/core33g/proprietary/bin/ext_data.sh:system/bin/ext_data.sh \
    vendor/samsung/core33g/proprietary/bin/ext_kill.sh:system/bin/ext_kill.sh \
    vendor/samsung/core33g/proprietary/bin/ext_symlink.sh:system/bin/ext_symlink.sh \
    vendor/samsung/core33g/proprietary/bin/prepare_param.sh:system/bin/prepare_param.sh \
    vendor/samsung/core33g/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/core33g/proprietary/lib/libreference-ril_sp.so:system/lib/libreference-ril_sp.so \
    vendor/samsung/core33g/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/core33g/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/core33g/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/core33g/proprietary/lib/libisp.so:system/lib/libisp.so \
    vendor/samsung/core33g/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/samsung/core33g/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so \
    vendor/samsung/core33g/proprietary/lib/hw/camera2.sc8830.so:system/lib/hw/camera2.sc8830.so \
    vendor/samsung/core33g/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
    vendor/samsung/core33g/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/core33g/proprietary/lib/libomafldrm.so:system/lib/libomafldrm.so \
    vendor/samsung/core33g/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/core33g/proprietary/lib/drm/libomaplugin.so:system/lib/drm/libomaplugin.so \
    vendor/samsung/core33g/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/samsung/core33g/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/core33g/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/core33g/proprietary/bin/lpm:system/bin/lpm \
    vendor/samsung/core33g/proprietary/lib/libQmageDecoder.so:system/lib/libQmageDecoder.so \
    vendor/samsung/core33g/proprietary/media/battery_charging_5.qmg:system/media/battery_charging_5.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_10.qmg:system/media/battery_charging_10.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_15.qmg:system/media/battery_charging_15.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_20.qmg:system/media/battery_charging_20.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_25.qmg:system/media/battery_charging_25.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_30.qmg:system/media/battery_charging_30.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_35.qmg:system/media/battery_charging_35.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_40.qmg:system/media/battery_charging_40.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_45.qmg:system/media/battery_charging_45.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_50.qmg:system/media/battery_charging_50.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_55.qmg:system/media/battery_charging_55.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_60.qmg:system/media/battery_charging_60.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_65.qmg:system/media/battery_charging_65.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_70.qmg:system/media/battery_charging_70.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_75.qmg:system/media/battery_charging_75.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_80.qmg:system/media/battery_charging_80.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_85.qmg:system/media/battery_charging_85.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_90.qmg:system/media/battery_charging_90.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_95.qmg:system/media/battery_charging_95.qmg \
    vendor/samsung/core33g/proprietary/media/battery_charging_100.qmg:system/media/battery_charging_100.qmg \
    vendor/samsung/core33g/proprietary/media/battery_batteryerror.qmg:system/media/battery_batteryerror.qmg \
    vendor/samsung/core33g/proprietary/media/battery_error.qmg:system/media/battery_error.qmg \
    vendor/samsung/core33g/proprietary/media/chargingwarning.qmg:system/media/chargingwarning.qmg \
    vendor/samsung/core33g/proprietary/media/Disconnected.qmg:system/media/Disconnected.qmg
